### PR TITLE
fix for file path encoding

### PR DESCRIPTION
**Pull request by nZo-sp**

### CODE REVIEW

**Review by azz — APPROVED** [review]

**Comment by azz** [comment]
Thanks for the fix!

**Comment by carusog** [comment]
Thanks for the fix Mr. @vincex It's much appreciated. And, btw, thank you for passing me the file before the pull request! 😄 😉

**Comment by carusog** [comment]
@azz it seems like current version doesn't have the fix by @vincex applied. Can you do that?
If you need help maintaining the plugin, just ask.

**Comment by azz** [comment]
Looks like this was merged to the wrong branch. I thought I set up automatic releases for this repo but it looks like I have not. I also haven't used this extension in a long time as my team has moved away from Visual Studio.

@carusog If you'd like to help maintain this extension that would be fantastic. I can add you as an author on the extension in VSIX.

**Comment by carusog** [comment]
@azz it'd my pleasure. Please, also add @vincex (he is a fellow of mines at my current company).
I'll do my best to help with it.

**Comment by azz** [comment]
Added you both as collaborators. I'm not at a computer right now so can't do the VSIX change yet, but feel free to get master in a releasable state.

**Pull request merged**
